// <auto-generated />
using System;
using BlogCMS.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogCMS.Core.Migrations
{
    [DbContext(typeof(BlogCMSContext))]
    partial class BlogCMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogCMS.Entites.Conrete.Authorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<int?>("ParentCommentId");

                    b.Property<int?>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cover");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Icon");

                    b.Property<string>("Name");

                    b.Property<int?>("Order");

                    b.Property<int?>("ParentMenuId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<string>("Cover");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Icon");

                    b.Property<int?>("MenuId");

                    b.Property<string>("Name");

                    b.Property<string>("Shortly");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Copyright");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Facebook");

                    b.Property<string>("Flickr");

                    b.Property<string>("Github");

                    b.Property<string>("Google");

                    b.Property<string>("Icon");

                    b.Property<string>("Instagram");

                    b.Property<string>("Linkedin");

                    b.Property<string>("Logo");

                    b.Property<string>("Pinterest");

                    b.Property<string>("Reddit");

                    b.Property<string>("SMTPHost");

                    b.Property<string>("SMTPPassword");

                    b.Property<string>("SMTPPort");

                    b.Property<string>("SMTPUser");

                    b.Property<string>("SiteTitle");

                    b.Property<string>("Slogan");

                    b.Property<string>("Snapchat");

                    b.Property<string>("Tumblr");

                    b.Property<string>("Twitter");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Url");

                    b.Property<string>("Whatsapp");

                    b.Property<string>("Youtube");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new { Id = 1, Copyright = "Ahmet Emin ŞİTe Aittir.", CreatedAt = new DateTime(2018, 10, 19, 11, 56, 1, 953, DateTimeKind.Local), Description = "Site Açıklaması Burada", Facebook = "Facebook Adresiniz", Flickr = "Flickr Adresiniz", Github = "Github Adresiniz.", Google = "Google Adresiniz.", Icon = "iconunuz", Instagram = "Instagram Adresiniz.", Linkedin = "Linkedin Adresiniz.", Logo = "Logo Adresiniz.", Pinterest = "Pinterest Adresiniz.", Reddit = "Reddit Adresiniz.", SMTPHost = "Host", SMTPPassword = "Pass", SMTPPort = "Port", SMTPUser = "User", SiteTitle = "Site Title", Slogan = "Slogan Buraya", Snapchat = "Snapchat Adresiniz.", Tumblr = "Tumblr Adresiniz.", Twitter = "Twitter Adresiniz.", UpdatedAt = new DateTime(2018, 10, 19, 11, 56, 1, 953, DateTimeKind.Local), Url = "URL Buraya", Whatsapp = "Whatsapp Adresiniz.", Youtube = "Youtube Adresiniz." }
                    );
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorizationId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.Comment", b =>
                {
                    b.HasOne("BlogCMS.Entites.Conrete.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("BlogCMS.Entites.Conrete.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("BlogCMS.Entites.Conrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.Menu", b =>
                {
                    b.HasOne("BlogCMS.Entites.Conrete.Menu", "ParentMenu")
                        .WithMany()
                        .HasForeignKey("ParentMenuId");
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.Post", b =>
                {
                    b.HasOne("BlogCMS.Entites.Conrete.Menu", "Menu")
                        .WithMany("Posts")
                        .HasForeignKey("MenuId");

                    b.HasOne("BlogCMS.Entites.Conrete.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BlogCMS.Entites.Conrete.User", b =>
                {
                    b.HasOne("BlogCMS.Entites.Conrete.Authorization", "Authorization")
                        .WithMany("Users")
                        .HasForeignKey("AuthorizationId");
                });
#pragma warning restore 612, 618
        }
    }
}
